# Plugins
whitelist           : []
plugins             : [jekyll-remote-theme]

# Conversion
markdown            : GFM
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

remote_theme: pages-themes/cayman@v0.2.0
title: [Bad Dragon Link Guide]