# Plugins
whitelist           : []
plugins             : [jekyll-remote-theme]

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

github:
  is_project_page: false

remote_theme: pages-themes/cayman@v0.2.0
repository: wahrt/Bad-Dragon-Link-Guide
title: [Bad Dragon Link Guide]